// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.toy.kotlinspringchat.proto;

public interface MessageArrProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.toy.kotlinspringchat.proto.MessageArrProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.toy.kotlinspringchat.proto.MessageProto msgList = 1;</code>
   */
  java.util.List<MessageProto>
      getMsgListList();
  /**
   * <code>repeated .com.toy.kotlinspringchat.proto.MessageProto msgList = 1;</code>
   */
  MessageProto getMsgList(int index);
  /**
   * <code>repeated .com.toy.kotlinspringchat.proto.MessageProto msgList = 1;</code>
   */
  int getMsgListCount();
  /**
   * <code>repeated .com.toy.kotlinspringchat.proto.MessageProto msgList = 1;</code>
   */
  java.util.List<? extends MessageProtoOrBuilder>
      getMsgListOrBuilderList();
  /**
   * <code>repeated .com.toy.kotlinspringchat.proto.MessageProto msgList = 1;</code>
   */
  MessageProtoOrBuilder getMsgListOrBuilder(
      int index);
}
