// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.toy.kotlinspringchat.proto;

public final class Chat {
  private Chat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_toy_kotlinspringchat_proto_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_toy_kotlinspringchat_proto_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_toy_kotlinspringchat_proto_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_toy_kotlinspringchat_proto_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nchat.proto\022\036com.toy.kotlinspringchat.p" +
      "roto\"n\n\007Message\022\017\n\007msgType\030\001 \001(\t\022\016\n\004data" +
      "\030\002 \001(\tH\000\0224\n\004user\030\003 \001(\0132$.com.toy.kotlins" +
      "pringchat.proto.UserH\000B\014\n\ndata_oneof\" \n\004" +
      "User\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\tB\002P\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_toy_kotlinspringchat_proto_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_toy_kotlinspringchat_proto_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_toy_kotlinspringchat_proto_Message_descriptor,
        new String[] { "MsgType", "Data", "User", "DataOneof", });
    internal_static_com_toy_kotlinspringchat_proto_User_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_toy_kotlinspringchat_proto_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_toy_kotlinspringchat_proto_User_descriptor,
        new String[] { "Id", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
