// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.toy.kotlinspringchat.proto;

/**
 * Protobuf type {@code com.toy.kotlinspringchat.proto.Message}
 */
public final class Message extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.toy.kotlinspringchat.proto.Message)
    MessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Message.newBuilder() to construct.
  private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Message() {
    msgType_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new Message();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Message(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            msgType_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();
            dataOneofCase_ = 2;
            dataOneof_ = s;
            break;
          }
          case 26: {
            User.Builder subBuilder = null;
            if (dataOneofCase_ == 3) {
              subBuilder = ((User) dataOneof_).toBuilder();
            }
            dataOneof_ =
                input.readMessage(User.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((User) dataOneof_);
              dataOneof_ = subBuilder.buildPartial();
            }
            dataOneofCase_ = 3;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Chat.internal_static_com_toy_kotlinspringchat_proto_Message_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Chat.internal_static_com_toy_kotlinspringchat_proto_Message_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Message.class, Builder.class);
  }

  private int dataOneofCase_ = 0;
  private Object dataOneof_;
  public enum DataOneofCase
      implements com.google.protobuf.Internal.EnumLite,
          InternalOneOfEnum {
    DATA(2),
    USER(3),
    DATAONEOF_NOT_SET(0);
    private final int value;
    private DataOneofCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static DataOneofCase valueOf(int value) {
      return forNumber(value);
    }

    public static DataOneofCase forNumber(int value) {
      switch (value) {
        case 2: return DATA;
        case 3: return USER;
        case 0: return DATAONEOF_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public DataOneofCase
  getDataOneofCase() {
    return DataOneofCase.forNumber(
        dataOneofCase_);
  }

  public static final int MSGTYPE_FIELD_NUMBER = 1;
  private volatile Object msgType_;
  /**
   * <code>string msgType = 1;</code>
   * @return The msgType.
   */
  @Override
  public String getMsgType() {
    Object ref = msgType_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      msgType_ = s;
      return s;
    }
  }
  /**
   * <code>string msgType = 1;</code>
   * @return The bytes for msgType.
   */
  @Override
  public com.google.protobuf.ByteString
      getMsgTypeBytes() {
    Object ref = msgType_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      msgType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATA_FIELD_NUMBER = 2;
  /**
   * <code>string data = 2;</code>
   * @return Whether the data field is set.
   */
  public boolean hasData() {
    return dataOneofCase_ == 2;
  }
  /**
   * <code>string data = 2;</code>
   * @return The data.
   */
  public String getData() {
    Object ref = "";
    if (dataOneofCase_ == 2) {
      ref = dataOneof_;
    }
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (dataOneofCase_ == 2) {
        dataOneof_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string data = 2;</code>
   * @return The bytes for data.
   */
  public com.google.protobuf.ByteString
      getDataBytes() {
    Object ref = "";
    if (dataOneofCase_ == 2) {
      ref = dataOneof_;
    }
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      if (dataOneofCase_ == 2) {
        dataOneof_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USER_FIELD_NUMBER = 3;
  /**
   * <code>.com.toy.kotlinspringchat.proto.User user = 3;</code>
   * @return Whether the user field is set.
   */
  @Override
  public boolean hasUser() {
    return dataOneofCase_ == 3;
  }
  /**
   * <code>.com.toy.kotlinspringchat.proto.User user = 3;</code>
   * @return The user.
   */
  @Override
  public User getUser() {
    if (dataOneofCase_ == 3) {
       return (User) dataOneof_;
    }
    return User.getDefaultInstance();
  }
  /**
   * <code>.com.toy.kotlinspringchat.proto.User user = 3;</code>
   */
  @Override
  public UserOrBuilder getUserOrBuilder() {
    if (dataOneofCase_ == 3) {
       return (User) dataOneof_;
    }
    return User.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msgType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, msgType_);
    }
    if (dataOneofCase_ == 2) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, dataOneof_);
    }
    if (dataOneofCase_ == 3) {
      output.writeMessage(3, (User) dataOneof_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msgType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, msgType_);
    }
    if (dataOneofCase_ == 2) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, dataOneof_);
    }
    if (dataOneofCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (User) dataOneof_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Message)) {
      return super.equals(obj);
    }
    Message other = (Message) obj;

    if (!getMsgType()
        .equals(other.getMsgType())) return false;
    if (!getDataOneofCase().equals(other.getDataOneofCase())) return false;
    switch (dataOneofCase_) {
      case 2:
        if (!getData()
            .equals(other.getData())) return false;
        break;
      case 3:
        if (!getUser()
            .equals(other.getUser())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getMsgType().hashCode();
    switch (dataOneofCase_) {
      case 2:
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
        break;
      case 3:
        hash = (37 * hash) + USER_FIELD_NUMBER;
        hash = (53 * hash) + getUser().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Message parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Message parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Message parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Message parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Message parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Message parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Message parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Message parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Message parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Message parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Message parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Message parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Message prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.toy.kotlinspringchat.proto.Message}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.toy.kotlinspringchat.proto.Message)
      MessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Chat.internal_static_com_toy_kotlinspringchat_proto_Message_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Chat.internal_static_com_toy_kotlinspringchat_proto_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Message.class, Builder.class);
    }

    // Construct using com.toy.kotlinspringchat.proto.Message.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      msgType_ = "";

      dataOneofCase_ = 0;
      dataOneof_ = null;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Chat.internal_static_com_toy_kotlinspringchat_proto_Message_descriptor;
    }

    @Override
    public Message getDefaultInstanceForType() {
      return Message.getDefaultInstance();
    }

    @Override
    public Message build() {
      Message result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public Message buildPartial() {
      Message result = new Message(this);
      result.msgType_ = msgType_;
      if (dataOneofCase_ == 2) {
        result.dataOneof_ = dataOneof_;
      }
      if (dataOneofCase_ == 3) {
        if (userBuilder_ == null) {
          result.dataOneof_ = dataOneof_;
        } else {
          result.dataOneof_ = userBuilder_.build();
        }
      }
      result.dataOneofCase_ = dataOneofCase_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Message) {
        return mergeFrom((Message)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Message other) {
      if (other == Message.getDefaultInstance()) return this;
      if (!other.getMsgType().isEmpty()) {
        msgType_ = other.msgType_;
        onChanged();
      }
      switch (other.getDataOneofCase()) {
        case DATA: {
          dataOneofCase_ = 2;
          dataOneof_ = other.dataOneof_;
          onChanged();
          break;
        }
        case USER: {
          mergeUser(other.getUser());
          break;
        }
        case DATAONEOF_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Message parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Message) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int dataOneofCase_ = 0;
    private Object dataOneof_;
    public DataOneofCase
        getDataOneofCase() {
      return DataOneofCase.forNumber(
          dataOneofCase_);
    }

    public Builder clearDataOneof() {
      dataOneofCase_ = 0;
      dataOneof_ = null;
      onChanged();
      return this;
    }


    private Object msgType_ = "";
    /**
     * <code>string msgType = 1;</code>
     * @return The msgType.
     */
    public String getMsgType() {
      Object ref = msgType_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        msgType_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string msgType = 1;</code>
     * @return The bytes for msgType.
     */
    public com.google.protobuf.ByteString
        getMsgTypeBytes() {
      Object ref = msgType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msgType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string msgType = 1;</code>
     * @param value The msgType to set.
     * @return This builder for chaining.
     */
    public Builder setMsgType(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      msgType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string msgType = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgType() {
      
      msgType_ = getDefaultInstance().getMsgType();
      onChanged();
      return this;
    }
    /**
     * <code>string msgType = 1;</code>
     * @param value The bytes for msgType to set.
     * @return This builder for chaining.
     */
    public Builder setMsgTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      msgType_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string data = 2;</code>
     * @return Whether the data field is set.
     */
    @Override
    public boolean hasData() {
      return dataOneofCase_ == 2;
    }
    /**
     * <code>string data = 2;</code>
     * @return The data.
     */
    @Override
    public String getData() {
      Object ref = "";
      if (dataOneofCase_ == 2) {
        ref = dataOneof_;
      }
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (dataOneofCase_ == 2) {
          dataOneof_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string data = 2;</code>
     * @return The bytes for data.
     */
    @Override
    public com.google.protobuf.ByteString
        getDataBytes() {
      Object ref = "";
      if (dataOneofCase_ == 2) {
        ref = dataOneof_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        if (dataOneofCase_ == 2) {
          dataOneof_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string data = 2;</code>
     * @param value The data to set.
     * @return This builder for chaining.
     */
    public Builder setData(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  dataOneofCase_ = 2;
      dataOneof_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string data = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearData() {
      if (dataOneofCase_ == 2) {
        dataOneofCase_ = 0;
        dataOneof_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string data = 2;</code>
     * @param value The bytes for data to set.
     * @return This builder for chaining.
     */
    public Builder setDataBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      dataOneofCase_ = 2;
      dataOneof_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        User, User.Builder, UserOrBuilder> userBuilder_;
    /**
     * <code>.com.toy.kotlinspringchat.proto.User user = 3;</code>
     * @return Whether the user field is set.
     */
    @Override
    public boolean hasUser() {
      return dataOneofCase_ == 3;
    }
    /**
     * <code>.com.toy.kotlinspringchat.proto.User user = 3;</code>
     * @return The user.
     */
    @Override
    public User getUser() {
      if (userBuilder_ == null) {
        if (dataOneofCase_ == 3) {
          return (User) dataOneof_;
        }
        return User.getDefaultInstance();
      } else {
        if (dataOneofCase_ == 3) {
          return userBuilder_.getMessage();
        }
        return User.getDefaultInstance();
      }
    }
    /**
     * <code>.com.toy.kotlinspringchat.proto.User user = 3;</code>
     */
    public Builder setUser(User value) {
      if (userBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dataOneof_ = value;
        onChanged();
      } else {
        userBuilder_.setMessage(value);
      }
      dataOneofCase_ = 3;
      return this;
    }
    /**
     * <code>.com.toy.kotlinspringchat.proto.User user = 3;</code>
     */
    public Builder setUser(
        User.Builder builderForValue) {
      if (userBuilder_ == null) {
        dataOneof_ = builderForValue.build();
        onChanged();
      } else {
        userBuilder_.setMessage(builderForValue.build());
      }
      dataOneofCase_ = 3;
      return this;
    }
    /**
     * <code>.com.toy.kotlinspringchat.proto.User user = 3;</code>
     */
    public Builder mergeUser(User value) {
      if (userBuilder_ == null) {
        if (dataOneofCase_ == 3 &&
            dataOneof_ != User.getDefaultInstance()) {
          dataOneof_ = User.newBuilder((User) dataOneof_)
              .mergeFrom(value).buildPartial();
        } else {
          dataOneof_ = value;
        }
        onChanged();
      } else {
        if (dataOneofCase_ == 3) {
          userBuilder_.mergeFrom(value);
        } else {
          userBuilder_.setMessage(value);
        }
      }
      dataOneofCase_ = 3;
      return this;
    }
    /**
     * <code>.com.toy.kotlinspringchat.proto.User user = 3;</code>
     */
    public Builder clearUser() {
      if (userBuilder_ == null) {
        if (dataOneofCase_ == 3) {
          dataOneofCase_ = 0;
          dataOneof_ = null;
          onChanged();
        }
      } else {
        if (dataOneofCase_ == 3) {
          dataOneofCase_ = 0;
          dataOneof_ = null;
        }
        userBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.toy.kotlinspringchat.proto.User user = 3;</code>
     */
    public User.Builder getUserBuilder() {
      return getUserFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.toy.kotlinspringchat.proto.User user = 3;</code>
     */
    @Override
    public UserOrBuilder getUserOrBuilder() {
      if ((dataOneofCase_ == 3) && (userBuilder_ != null)) {
        return userBuilder_.getMessageOrBuilder();
      } else {
        if (dataOneofCase_ == 3) {
          return (User) dataOneof_;
        }
        return User.getDefaultInstance();
      }
    }
    /**
     * <code>.com.toy.kotlinspringchat.proto.User user = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        User, User.Builder, UserOrBuilder>
        getUserFieldBuilder() {
      if (userBuilder_ == null) {
        if (!(dataOneofCase_ == 3)) {
          dataOneof_ = User.getDefaultInstance();
        }
        userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            User, User.Builder, UserOrBuilder>(
                (User) dataOneof_,
                getParentForChildren(),
                isClean());
        dataOneof_ = null;
      }
      dataOneofCase_ = 3;
      onChanged();;
      return userBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.toy.kotlinspringchat.proto.Message)
  }

  // @@protoc_insertion_point(class_scope:com.toy.kotlinspringchat.proto.Message)
  private static final Message DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Message();
  }

  public static Message getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Message>
      PARSER = new com.google.protobuf.AbstractParser<Message>() {
    @Override
    public Message parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Message(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Message> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Message> getParserForType() {
    return PARSER;
  }

  @Override
  public Message getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

