// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.toy.kotlinspringchat.proto;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.toy.kotlinspringchat.proto.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msgType = 1;</code>
   * @return The msgType.
   */
  String getMsgType();
  /**
   * <code>string msgType = 1;</code>
   * @return The bytes for msgType.
   */
  com.google.protobuf.ByteString
      getMsgTypeBytes();

  /**
   * <code>string data = 2;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>string data = 2;</code>
   * @return The data.
   */
  String getData();
  /**
   * <code>string data = 2;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();

  /**
   * <code>.com.toy.kotlinspringchat.proto.User user = 3;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.com.toy.kotlinspringchat.proto.User user = 3;</code>
   * @return The user.
   */
  User getUser();
  /**
   * <code>.com.toy.kotlinspringchat.proto.User user = 3;</code>
   */
  UserOrBuilder getUserOrBuilder();

  public Message.DataOneofCase getDataOneofCase();
}
