// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.toy.kotlinspringchat.proto;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.toy.kotlinspringchat.proto.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
