// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.toy.stompchat.proto;

public final class Chat {
  private Chat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_toy_stompchat_proto_MessageProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_toy_stompchat_proto_MessageProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_toy_stompchat_proto_UserProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_toy_stompchat_proto_UserProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_toy_stompchat_proto_MessageArrProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_toy_stompchat_proto_MessageArrProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nchat.proto\022\027com.toy.stompchat.proto\"\245\001" +
      "\n\014MessageProto\0225\n\007msgType\030\001 \001(\0162$.com.to" +
      "y.stompchat.proto.MsgTypeEnum\022\016\n\004data\030\002 " +
      "\001(\tH\000\0222\n\004user\030\003 \001(\0132\".com.toy.stompchat." +
      "proto.UserProtoH\000\022\014\n\004date\030\004 \001(\003B\014\n\ndata_" +
      "oneof\"&\n\tUserProto\022\013\n\003idx\030\001 \001(\003\022\014\n\004name\030" +
      "\002 \001(\t\"I\n\017MessageArrProto\0226\n\007msgList\030\001 \003(" +
      "\0132%.com.toy.stompchat.proto.MessageProto" +
      "**\n\013MsgTypeEnum\022\010\n\004JOIN\020\000\022\010\n\004LEFT\020\001\022\007\n\003S" +
      "AY\020\002B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_toy_stompchat_proto_MessageProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_toy_stompchat_proto_MessageProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_toy_stompchat_proto_MessageProto_descriptor,
        new String[] { "MsgType", "Data", "User", "Date", "DataOneof", });
    internal_static_com_toy_stompchat_proto_UserProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_toy_stompchat_proto_UserProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_toy_stompchat_proto_UserProto_descriptor,
        new String[] { "Idx", "Name", });
    internal_static_com_toy_stompchat_proto_MessageArrProto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_toy_stompchat_proto_MessageArrProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_toy_stompchat_proto_MessageArrProto_descriptor,
        new String[] { "MsgList", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
