// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.toy.stompchat.proto;

/**
 * Protobuf enum {@code com.toy.stompchat.proto.MsgTypeEnum}
 */
public enum MsgTypeEnum
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>JOIN = 0;</code>
   */
  JOIN(0),
  /**
   * <code>LEFT = 1;</code>
   */
  LEFT(1),
  /**
   * <code>SAY = 2;</code>
   */
  SAY(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>JOIN = 0;</code>
   */
  public static final int JOIN_VALUE = 0;
  /**
   * <code>LEFT = 1;</code>
   */
  public static final int LEFT_VALUE = 1;
  /**
   * <code>SAY = 2;</code>
   */
  public static final int SAY_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static MsgTypeEnum valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static MsgTypeEnum forNumber(int value) {
    switch (value) {
      case 0: return JOIN;
      case 1: return LEFT;
      case 2: return SAY;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MsgTypeEnum>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MsgTypeEnum> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MsgTypeEnum>() {
          public MsgTypeEnum findValueByNumber(int number) {
            return MsgTypeEnum.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return Chat.getDescriptor().getEnumTypes().get(0);
  }

  private static final MsgTypeEnum[] VALUES = values();

  public static MsgTypeEnum valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private MsgTypeEnum(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.toy.stompchat.proto.MsgTypeEnum)
}

