// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.toy.stompchat.proto;

public interface UserProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.toy.stompchat.proto.UserProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 idx = 1;</code>
   * @return The idx.
   */
  long getIdx();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
